#cloud-config
packages:
  - curl
  - unzip
  - gpg
  - coreutils
  - apt-transport-https 
  - ca-certificates
  - software-properties-common
package_update: true
package_upgrade: true
write_files:
  - path: /etc/nomad.d/nomad.hcl
    content: |
      # Full configuration options can be found at https://www.nomadproject.io/docs/configuration

      data_dir  = "/opt/nomad/data"
      bind_addr = "0.0.0.0"

      server {
        enabled          = true
        bootstrap_expect = 1
      }

      client {
        enabled = true
        servers = ["127.0.0.1"]
      }

      plugin "docker" {
          volumes {
            enabled = true
          }
      }

      plugin "raw_exec" {
        config {
          enabled = true
        }
      }

      acl {
        enabled = true
      }

      telemetry {
        collection_interval = "1s"
        disable_hostname = true
        prometheus_metrics = true
        publish_allocation_metrics = true
        publish_node_metrics = true
      }
runcmd:
  # install nomad
  - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
  - apt-get update && apt-get install nomad
  - curl -L -o cni-plugins.tgz "https://github.com/containernetworking/plugins/releases/download/v1.0.0/cni-plugins-linux-$( [ $(uname -m) = aarch64 ] && echo arm64 || echo amd64)"-v1.0.0.tgz && \
  
  - mkdir -p /opt/cni/bin && \
  - tar -C /opt/cni/bin -xzf cni-plugins.tgz
  - systemctl enable nomad
  - systemctl start nomad

  # install docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update && apt-get install docker-ce
  - systemctl enable docker
  - systemctl start docker
  
  # configure ufw
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow 22/tcp
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw allow 4646:4648/tcp
  - ufw allow 4648/udp
  - ufw enable
  - ufw status
  - systemctl start ufw.service
  - systemctl status ufw.service
